mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      "gps_baro",
    ]

    initial_state_estimator: "gps_baro" # will be used as the first state estimator
    agl_height_estimator: "" # only slightly filtered height for checking min height (not used in control feedback)

  uav_manager:

    min_height_checking:
      enabled: false

    max_height_checking:
      enabled: false

  constraint_manager:

    default_constraints:
      gps_baro: "fast"


mrs_uav_trackers:

 mpc_tracker:

   collision_avoidance:

     enabled: true # disabling this will stop this UAV to react to others, but it will still transmit data to others
     radius: 2.0 # [m]
