simulation_rate: 100.0
clock_rate: 100.0
realtime_factor: 0.5

iterate_without_input: true

individual_takeoff_platform:
  enabled: false

collisions:
  enabled: true
  crash: false

  # if crash==false, then the collisions are elastic
  rebounce: 100.0

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: false
  
  bounds:
    x: 5.0
    y: 5.0
    z: 15.0

ground:
  enabled: true
  z: 0.0 # [m]

uav_names: [
  "uav1",
  "uav3",
  "uav7",
  "uav8",
  "uav31",
  "uav32",
  #"uav37",
]

uav1:
  type: "x500"
  spawn:
    x: -50.0
    y: 10.0
    z: 2.0
    heading: 0

uav3:
  type: "x500"
  spawn:
    x: -40.0
    y: 10.0
    z: 2.0
    heading: 0

uav7:
  type: "x500"
  spawn:
    x: -30.0
    y: 10.0
    z: 2.0
    heading: 0

uav8:
  type: "x500"
  spawn:
    x: -50.0
    y: 20.0
    z: 2.0
    heading: 0

uav31:
  type: "x500"
  spawn:
    x: -40.0
    y: 20.0
    z: 2.0
    heading: 0

uav32:
  type: "x500"
  spawn:
    x: -30.0
    y: 20.0
    z: 2.0
    heading: 0

#uav37:
#  type: "x500"
#  spawn:
#    x: -50.0
#    y: 30.0
#    z: 2.0
#    heading: 0

